basePath: /api/v1
definitions:
  models.CapacityResult:
    properties:
      1_lsb:
        type: integer
      2_lsb:
        type: integer
      3_lsb:
        type: integer
      4_lsb:
        type: integer
    type: object
  models.ErrorDetail:
    properties:
      details:
        additionalProperties: true
        type: object
      message:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      error:
        $ref: '#/definitions/models.ErrorDetail'
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/capacity:
    post:
      consumes:
      - multipart/form-data
      description: Calculates the maximum size of a secret file (in bytes) that can
        be embedded into an uploaded MP3 file using the multiple-LSB method. The capacity
        is returned for 1, 2, 3, and 4 LSBs.
      parameters:
      - description: MP3 audio file to calculate capacity for.
        in: formData
        name: audio
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Successfully calculated embedding capacity.
          schema:
            $ref: '#/definitions/models.CapacityResult'
        "400":
          description: 'Bad Request: No file uploaded, file is not an MP3, or file
            is corrupted.'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 'Internal Server Error: Failed to process the file.'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Calculate Audio Embedding Capacity
      tags:
      - Steganography
  /api/embed:
    post:
      consumes:
      - multipart/form-data
      description: Embeds a secret file into an MP3 cover audio file using the multiple-LSB
        steganography method. Supports encryption with extended Vigenère cipher, random
        starting position, and configurable LSB depth (1-4 bits). Returns the stego-audio
        file with PSNR quality measurement.
      parameters:
      - description: MP3 cover audio file to embed the secret message into
        in: formData
        name: cover_audio
        required: true
        type: file
      - description: Secret file to be hidden (any file type and size)
        in: formData
        name: secret_file
        required: true
        type: file
      - description: Steganography key used for encryption and random seed generation
          (max 25 characters)
        in: formData
        name: stego_key
        required: true
        type: string
      - description: Number of LSB bits to use for embedding (1, 2, 3, or 4)
        enum:
        - 1
        - 2
        - 3
        - 4
        in: formData
        name: n_lsb
        required: true
        type: integer
      - description: Whether to encrypt the secret file using Vigenère cipher
        enum:
        - "true"
        - "false"
        in: formData
        name: use_encryption
        required: true
        type: string
      - description: Whether to use random starting position for embedding
        enum:
        - "true"
        - "false"
        in: formData
        name: use_random_start
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: Successfully embedded message into audio file. Returns stego-audio
            MP3 file.
          headers:
            Content-Disposition:
              description: attachment; filename=\"filename_stego.mp3\
              type: string
            Content-Type:
              description: application/octet-stream
              type: string
            X-PSNR-Value:
              description: Peak Signal-to-Noise Ratio value (e.g., \"38.54\")
              type: string
          schema:
            type: file
        "400":
          description: 'Bad Request: Missing required parameters, invalid file format,
            or invalid parameter values'
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "413":
          description: 'Payload Too Large: Secret file size exceeds embedding capacity'
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: 'Internal Server Error: Failed to process files or embed message'
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Embed Secret Message into Audio File
      tags:
      - Steganography
swagger: "2.0"
